# https://github.com/chainguard-dev/apko/blob/main/docs/apko_file.md
# https://github.com/chainguard-images/images/blob/main/BEST_PRACTICES.md
# https://github.com/wolfi-dev/os/blob/main/php-8.4.yaml
# https://images.chainguard.dev/directory/image/php/specifications
# https://images.chainguard.dev/directory/image/php/sbom
# https://github.com/chainguard-images/images/blob/main/images/php/config/fpm/main.tf
# https://github.com/chainguard-images/images/blob/main/images/php/fpm.tf
contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - ca-certificates-bundle
    - wolfi-baselayout
    - glibc-locale-posix
    - ca-certificates
    - curl
    - php-8.5
    - php-8.5-fpm
    - php-8.5-curl
    - php-8.5-openssl
    - php-8.5-mbstring
    - php-8.5-iconv
    - php-8.5-mysqlnd
    - php-8.5-pdo
    - php-8.5-pdo_mysql
    - php-8.5-pdo_sqlite
    - php-8.5-sodium
    - php-8.5-phar
    # Additional extensions
    # - php-8.5-apache
    # - php-8.5-apcu
    # - php-8.5-gd
    # - php-8.5-grpc
    # - php-8.5-igbinary
    # - php-8.5-intl
    # - php-8.5-opcache
    # - php-8.5-opentelemetry
    # - php-8.5-pcntl
    # - php-8.5-pdo_pgsql
    # - php-8.5-protobuf
    # - php-8.5-redis
    # - php-8.5-swoole
    # - php-8.5-zip
    # - php-8.5-zstd
    # - php-8.5-xdebug
    # dev
    - apk-tools
    - busybox
    - bash
    - git
    - wget
    - composer

environment:
  PATH: /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
  SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt

entrypoint:
  type: service-bundle
  services:
    php-fpm: /usr/bin/php-fpm

paths:
  - path: /app
    type: directory
    permissions: 511 # 0777
    uid: 65532
    gid: 65532

work-dir: /app

accounts:
  groups:
    - groupname: php
      gid: 65532
  users:
    - username: php
      uid: 65532
      gid: 65532
  run-as: 65532

archs:
  - x86_64
  - aarch64
