# https://github.com/chainguard-dev/apko/blob/main/docs/apko_file.md
# https://github.com/chainguard-images/images/blob/main/BEST_PRACTICES.md
contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - ca-certificates-bundle
    - wolfi-baselayout
    - glibc-locale-posix
    # - tzdata
environment:
  PATH: /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
  SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt

archs:
  - x86_64
  - aarch64
