# https://github.com/chainguard-dev/apko/blob/main/docs/apko_file.md
# https://github.com/chainguard-images/images/blob/main/BEST_PRACTICES.md
# https://github.com/wolfi-dev/os/blob/main/caddy.yaml
# https://images.chainguard.dev/directory/image/caddy/specifications
# https://images.chainguard.dev/directory/image/caddy/sbom
includes: .base.yaml
contents:
  packages:
    - caddy

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      gid: 65532
  run-as: 65532

entrypoint:
  command: /usr/bin/caddy

cmd: run
