# https://github.com/chainguard-dev/apko/blob/main/docs/apko_file.md
# https://github.com/chainguard-images/images/blob/main/BEST_PRACTICES.md
# https://github.com/wolfi-dev/os/blob/main/nodejs-24.yaml
# https://github.com/chainguard-images/images/blob/main/images/node/config/main.tf
# https://github.com/chainguard-images/images/blob/main/images/node/main.tf
# https://images.chainguard.dev/directory/image/node/sbom
# https://images.chainguard.dev/directory/image/node/specifications
contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - ca-certificates-bundle
    - wolfi-baselayout
    - glibc-locale-posix
    - nodejs-24
    - dumb-init
    - busybox
    - nghttp2
    - npm
    # dev
    - build-base
    - corepack
    - pnpm
    - yarn
    - apk-tools
    - busybox
    - bash
    - git
    - wget

entrypoint:
  command: /usr/bin/node
cmd: --help

environment:
  # NODE_PORT: 3000
  NPM_CONFIG_UPDATE_NOTIFIER: false # Disables npm update notifications
  PATH: /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
  SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt

work-dir: /app

accounts:
  groups:
    - groupname: node
      gid: 65532
  users:
    - username: node
      uid: 65532
  run-as: 65532

paths:
  - path: /app
    type: directory
    permissions: 511 # 0777
    uid: 65532
    gid: 65532

archs:
  - x86_64
  - aarch64
