user nginx;

# Sets the worker threads to the number of CPU cores available in the system for
# best performance. Should be > the number of CPU cores.
# Maximum number of connections = worker_processes * worker_connections
# https://nginx.org/en/docs/ngx_core_module.html#worker_processes
worker_processes auto;

# Also set
# /etc/security/limits.conf
#   nginx soft nofile 65535
#   nginx hard nofile 65535
# /etc/default/nginx
#       ULIMIT="-n 65535"
worker_rlimit_nofile 65535;

# Set the error log to write to stderr with a log level of "notice". This is
# important for Docker, as it allows the logs to be captured by the Docker logging driver.
error_log /dev/stderr notice;

pid /run/nginx.pid;

# Disable nginx daemon mode, because using docker we need foreground process
daemon off;

events {
    use epoll;
    worker_connections 4096;
}

http {

    # https://www.iana.org/assignments/media-types/media-types.xhtml
    include /etc/nginx/mime.types;

    default_type application/octet-stream;

    # Prevent Nginx from sending its version number in the "Server" response header.
    server_tokens off;

    log_format main
        '$remote_addr - $remote_user [$time_local] "$request" '
        '$status $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"';

    # Set the access log to write to stdout, which is important for Docker, as it allows the logs to be captured by the Docker logging driver.
    access_log /dev/stdout;

    # client_body_buffer_size 8k;
    # client_header_buffer_size 1k;
    # large_client_header_buffers 4 8k;
    # client_max_body_size 1M;
    # types_hash_max_size 1024;

    # Speed up file transfers by using `sendfile()` to copy directly between
    # descriptors rather than using `read()`/`write()``.
    # https://nginx.org/en/docs/http/ngx_http_core_module.html#sendfile
    sendfile on;

    # Don't send out partial frames; this increases throughput since TCP frames
    # are filled up before being sent out.
    # https://nginx.org/en/docs/http/ngx_http_core_module.html#tcp_nopush
    tcp_nopush on;

    # Don't buffer data-sends (disable Nagle algorithm). Good for sending
    # frequent small bursts of data in real time.
    # https://nginx.org/en/docs/http/ngx_http_core_module.html#tcp_nodelay
    tcp_nodelay on;

    # Keep connections alive for 65 seconds. This is a good value for most applications, as it allows clients to reuse connections without keeping them open for too long.
    keepalive_timeout 65s;
    keepalive_requests 10000;

    # Reduce the time nginx waits for a client to acknowledge or send data before closing the connection. This can help free up resources more quickly if clients are slow or unresponsive.
    # https://nginx.org/en/docs/http/ngx_http_core_module.html#reset_timedout_connection
    reset_timedout_connection on;

    # If a client stops sending data, close the connection after 10 seconds.
    client_body_timeout 10s;
    client_header_timeout 10s;

    # If a client stops receiving data, close the connection after 10 seconds.
    # https://nginx.org/en/docs/http/ngx_http_core_module.html#send_timeout
    send_timeout 10s;

    #gzip  on;
    include /etc/nginx/conf.d/*.conf;
}
