# https://github.com/wolfi-dev/os/blob/main/percona-server-9.1.yaml
# https://github.com/wolfi-dev/os/blob/main/percona-server-9.1/docker-entrypoint.sh
# https://images.chainguard.dev/directory/image/percona-server/specifications
# https://images.chainguard.dev/directory/image/percona-server/sbom
contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - ca-certificates-bundle
    - wolfi-baselayout
    - glibc-locale-posix
    - tzdata
    - percona-server-8.4
    - percona-server-8.4-oci-entrypoint

accounts:
  groups:
    - groupname: mysql
      gid: 65532
  users:
    - username: mysql
      uid: 65532
  run-as: 65532

entrypoint:
  command: /docker-entrypoint.sh mysqld

environment:
  PATH: /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
  SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt

paths:
  - path: /var/lib/mysql
    type: directory
    permissions: 511 # 0777
    uid: 65532
    gid: 65532
  - path: /var/tmp
    type: directory
    permissions: 511 # 0777
    uid: 65532
    gid: 65532
  - path: /run/mysqld
    type: directory
    permissions: 511 # 0777
    uid: 65532
    gid: 65532
  - path: /docker-entrypoint-initdb.d
    type: directory
    permissions: 511 # 0777
    uid: 65532
    gid: 65532

archs:
  - x86_64
  # - aarch64
